# Generated by Django 3.0 on 2020-09-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
